define([], function() {
  return {
    "PropertyPaneDescription": "Configurez le formulaire de la liste ici. Une fois la liste configurée, les champs peuvent être déplacés, insérés et supprimés dans le contenu du webpart",
    "Loading": "Loading...",
    "GenericErrorMessage": "An error occured, please contact administrator.",
    "HomeNav":"Home",
    "SemisNav": "Semis Management",
    "NewEditNav": "Farming Management",
    "ArchiveNav": "Archive Farming",
    'BasicGroupName': 'Paramètres',
    'TitleFieldLabel': 'Titre',
    'DescriptionFieldLabel': 'Description',
    'GroupeFieldLabel': 'Security group',
    'ListFieldLabel': 'suivi List',
    'SemisListFiedLabel' : 'semis List',
    'FormTypeFieldLabel': 'Formular Type',
    'CreationModeLabel': 'Display mode',
    'ItemIdFieldLabel': 'ID de l\'item',
    'ItemIdFieldDescription' : 'Entrez un nombre pour l\'ID ou le nom du paramètre de chaîne de requête à utiliser pour l\'ID.',
    'ShowUnsupportedFieldsLabel': 'Afficher les champs non pris en charge',
    'RedirectUrlFieldLabel': 'URL de redirection après l\'enregistrement (facultatif)',
    'RedirectUrlFieldDescription': 'Peut contenir [ID] comme placeholder remplacable par l\'ID de l\'élément mis à jour ou créé. Exemple: /list/Test/DispForm.aspx?ID=[ID]',
    'LocalWorkbenchUnsupported': 'L\'exécution du WebPart dans votre Workbench local n\'est pas prise en charge. Veuillez l\'exécuter dans votre site SharePoint.',
    'MissingListConfiguration': 'Please configure SharePoint List in WebPart properties.',
    'ConfigureWebpartButtonText': 'Configure WebPart',
    'ErrorOnLoadingLists': 'Error when loading Lists : ',
    'MessageLoading' : 'WebPart Loading in progress...',
    'SearchPlaceHolder': 'Filter',
    'RecolteDialogTitle' : 'Gathering',
    'RecolteDialogPoid' : 'harvest weight (kg)',
    'RecolteDialogComment': 'harvest comment',
    'GoToDialogTitle': 'Go to zipGrow',
    'GoToDialogSelect': 'Select zipGrow'
  }
});