define([], function() {
  return {
    "BasicGroupName": "Nom du groupe",
    "DescriptionFieldLabel": "Champs Description",
    "Loading": "Chargement...",
    "GenericErrorMessage": "Une erreur s'est produite, veuillez contacter l'administrateur.",
    "HubErrorMessage": "La configuration provenant de MyFood ne semble pas disponible !",
    "HomeNav":"Accueil",
    "SemisNav": "Semis",
    "NewEditNav": "Cultures",
    "ArchiveNav": "Archives",
    'PropertyPaneDescription': 'Configurez le formulaire de la liste ici. Une fois la liste configurée, les champs peuvent être déplacés, insérés et supprimés dans le contenu du webpart.',
    'BasicGroupName': 'Paramètres',
    'TitleFieldLabel': 'Titre',
    'DescriptionFieldLabel': 'Description',
    'GroupeFieldLabel': 'Groupe de securité',
    'ListFieldLabel': 'Liste suivi',
    'SemisListFiedLabel' : 'Liste semis',
    'FormTypeFieldLabel': 'Type de formulaire',
    'CreationModeLabel': 'Mode affichage',
    'ItemIdFieldLabel': 'ID de l\'item',
    'ItemIdFieldDescription' : 'Entrez un nombre pour l\'ID ou le nom du paramètre de chaîne de requête à utiliser pour l\'ID.',
    'ShowUnsupportedFieldsLabel': 'Afficher les champs non pris en charge',
    'RedirectUrlFieldLabel': 'URL de redirection après l\'enregistrement (facultatif)',
    'RedirectUrlFieldDescription': 'Peut contenir [ID] comme placeholder remplacable par l\'ID de l\'élément mis à jour ou créé. Exemple: /list/Test/DispForm.aspx?ID=[ID]',
    'LocalWorkbenchUnsupported': 'L\'exécution du WebPart dans votre Workbench local n\'est pas prise en charge. Veuillez l\'exécuter dans votre site SharePoint.',
    'MissingListConfiguration': 'Veuillez configurer une liste SharePoint dans les propriétés du WebPart.',
    'ConfigureWebpartButtonText': 'Configurer le WebPart',
    'ErrorOnLoadingLists': 'Erreur de chargement des listes : ',
    'MessageLoading' : 'Chargement de la webPart en cours...',
    'SearchPlaceHolder': 'Filtrer',
    'RecolteDialogTitle' : 'Recolter la culture',
    'RecolteDialogPoid' : 'Poid de récolte (kg)',
    'RecolteDialogComment': 'Commentaire de récolte',
    'GoToDialogTitle': 'Basculter en culture',
    'GoToDialogSelect': 'Selectionner un emplacement',
    'GrowingTypeText': 'Culture en : ',
    'serreTypeTitle' : 'Selectionner votre configuration'
  }
});